### ISSUE TITLE
testModifyUser function has some error

### ISSUE THREAD

**Issue by Linvery** [casdoor/casdoor-php-sdk#24]
![image](https://user-images.githubusercontent.com/23356865/186727201-de044e29-eba3-4b96-92d1-263c00f18d25.png)
![image](https://user-images.githubusercontent.com/23356865/186727252-e260593a-f7c2-406e-8ca4-672c7418b27a.png)
![image](https://user-images.githubusercontent.com/23356865/186727319-a486bea0-08b2-411e-828e-7a9027e5d5fc.png)

I try to Modify "displayname",Then it reported an error.

**Comment by hsluoyz** [comment]
@basakest

**Comment by hsluoyz** [comment]
@Linvery can you show your error call stack in casdoor-php-sdk?

**Comment by Linvery** [comment]
> @Linvery can you show your error call stack in casdoor-php-sdk?

The third picture is all the information about error reporting that I can see

**Comment by Linvery** [comment]
> @Linvery你能在 casdoor-php-sdk 中显示你的错误调用堆栈吗？

The controller only calls the function named updateuser. The parameters passed in the apibox are not important

**Comment by Linvery** [comment]
> @Linvery can you show your error call stack in casdoor-php-sdk?

My PHP version is 8.0

**Comment by Linvery** [comment]
#25 I proposed a PR so that it can work normally in php8.0.At the same time, I'm a new git user. Maybe I made some mistakes

**Comment by hsluoyz** [comment]
@Linvery can you make a PR to fix this issue?

**Comment by Linvery** [comment]
> @Linvery can you make a PR to fix this issue?

fixed
https://github.com/casdoor/casdoor-php-sdk/pull/25

**Comment by hsluoyz** [comment]
@Linvery hi, can you join our QQ group: 645200447 ?

**Comment by Linvery** [comment]
> @Linvery hi, can you join our QQ group: 645200447 ?

Yes,I have joined.
