### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-php-sdk#28]
Like: https://github.com/php-casbin/php-casbin

![image](https://user-images.githubusercontent.com/3787410/189123995-1b57ce22-39a3-4f62-bc38-0ee0f58bdd44.png)

**Comment by hsluoyz** [comment]
@Linvery

**Comment by Linvery** [comment]
The badge is generated from here
https://poser.pugx.org/show/casdoor/casdoor-php-sdk

**Comment by Linvery** [comment]
@hsluoyz #32 Completed
