### ISSUE TITLE
PHP-Casdoor-SDK can't create application

### ISSUE THREAD

**Issue by Yamituki** [casdoor/casdoor-php-sdk#30]
class OauthTest extends TestCase
{
    private array $config;

    private AuthConfig $auth;

    #[PostMapping(path: '/api/system/backend/site/casdoor')]
    public function __invoke(): void
    {
        $this->config = [
            'endpoint' => 'http://localhost:9501',
            'clientId' => '',
            'clientSecret' => '',
            'jwtPublicKey' => '',
            'organizationName' => '',
            'applicationName' => '',
        ];
        $this->auth = new AuthConfig(...$this->config);
        $app = new Application('', '');
        $app->addApplication($app, $this->auth);
    }
}

This is my code， and this is error message.

[CRITICAL] Error: Call to undefined function GuzzleHttp\Psr7\get_message_body_summary() in /opt/www/vendor/gb-hyperf/framework/src/Exception/Handler/GuzzleRequestExceptionHandler.php:38
Stack trace:
#0 /opt/www/vendor/hyperf/exception-handler/src/ExceptionHandlerDispatcher.php(43): Gb\Framework\Exception\Handler\GuzzleRequestExceptionHandler->handle()
casdoor/casdoor#1 /opt/www/vendor/hyperf/http-server/src/Server.php(87): Hyperf\ExceptionHandler\ExceptionHandlerDispatcher->dispatch()
casdoor/casdoor#2 /opt/www/vendor/hyperf/utils/src/SafeCaller.php(29): Hyperf\HttpServer\Server->Hyperf\HttpServer\{closure}()
casdoor/casdoor#3 /opt/www/vendor/hyperf/http-server/src/Server.php(90): Hyperf\Utils\SafeCaller->call()
casdoor/casdoor#4 [internal function]: Hyperf\HttpServer\Server->onRequest()
casdoor/casdoor#5 {main}
<img width="1440" alt="D02FC2A1E633EC37A405DF95BA9962B3" src="https://user-images.githubusercontent.com/48856361/190462356-640b373b-ae0b-4e79-85df-7459e9a37db8.png">

**Comment by hsluoyz** [comment]
@Linvery

**Comment by Linvery** [comment]
![image](https://user-images.githubusercontent.com/23356865/190661326-543c21be-1f9d-4c73-af54-cb4c482aa0be.png)
![image](https://user-images.githubusercontent.com/23356865/190661594-56866153-dbdc-4172-82be-1d451578a6f8.png)
![image](https://user-images.githubusercontent.com/23356865/190661688-ae8667b8-7ebe-4478-a46b-a644b5b462b1.png)
This is really a bug with incomplete code,The code in Figure 1 can add applications, but this is not perfect. It does not add complete fields in the database, and will cause blank rendering of the Castle. This problem needs to be further fixed.

**Comment by Linvery** [comment]
@Yamituki #31 I fixed it. Can you help me test it?

**Comment by Linvery** [comment]
@Yamituki You can use this example
```php
<?php

namespace Casdoor\Tests;

use Casdoor\Auth\Application;

class ApplicationTest
{
    public function initConfig()
    {
        $endpoint = 'http://127.0.0.1:8000';
        $clientId = '6a4030b5f9fd3d00456f';
        $clientSecret = '5b17bf8c0505d94d5de7615f030bf3f8a9c0d8a0';
        $jwtSecret = file_get_contents(dirname(__FILE__) . '/public_key.pem');
        $organizationName = 'built-in';
        $applicationName = 'testApp';
        Application::initConfig($endpoint, $clientId, $clientSecret, $jwtSecret, $organizationName, $applicationName);
    }

    /**
     * Default applicationConfig parameters
     */
    public function applicationConfig(){
        $app = new Application(User::$authConfig);
        $app->name = "default";
        $app->displayname=$app->name;
        $app->owner = "admin";
        $app->providers=[["name" => "provider_captcha_default", "canSignUp" => false, "canSignIn" => false, "canUnlink" => false, "prompted" => false, "alertType" => "None"]];
        $app->logo = "https://cdn.casbin.org/img/casdoor-logo_1185x256.png";
        $app->organization = "built-in";
        $app->cert = "cert-built-in";
        $app->redirectUris = ["http://localhost:9000/callback"];
        $app->tokenFormat = "JWT";
        $app->expireInHours = 168;
        $app->formOffset = 8;
        $app->signupItems = [
            [
                "name" => "ID",
                "visible" => false,
                "required" => true,
                "rule" => "Random"
            ],
            [
                "name" => "Username",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ],
            [
                "name" => "Display name",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ],
            [
                "name" => "Password",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ],
            [
                "name" => "Confirm password",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ],
            [
                "name" => "Email",
                "visible" => true,
                "required" => true,
                "rule" => "Normal"
            ],
            [
                "name" => "Phone",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ],
            [
                "name" => "Agreement",
                "visible" => true,
                "required" => true,
                "rule" => "None"
            ]
        ];
        $app->enablePassword = true;
        $app->enableSignUp = true;
        $app->enableSigninSession = false;
        $app->enableCodeSignin = false;
        $app->enableSamlCompress = false;
        return $app;
    }

    public function addApplication(){
        $this->initConfig();
        $app = $this->applicationConfig();
        $app->name="testApp";   # Modify config parameters
        $app->displayname="testCompanyApp";
        $res = $app->addApplication();
    }

    public function deleteApplication(){
        $this->initConfig();
        $app = $this->applicationConfig();
        $app->name="testApp";   # Modify config parameters
        $res = $app->deleteApplication();
    }
}
```
