### ISSUE TITLE
Auth/Url.php line24      getSigninUrl  There is a method that is not a static method      

### ISSUE THREAD

**Issue by yangguangwuwu** [casdoor/casdoor-php-sdk#33]
Auth/Url.php line24      getSigninUrl  There is a method that is not a static method

**Comment by hsluoyz** [comment]
@Linvery

**Comment by Linvery** [comment]
@yangguangwuwu Can you show the code of your application scenario?

**Comment by Linvery** [comment]
![image](https://user-images.githubusercontent.com/23356865/191496960-1eac0621-ed9f-4aa4-ae13-58bf79acaf03.png)

**Comment by Linvery** [comment]
#34 Fixed
