### ISSUE TITLE
syntax error, unexpected 'array' in php 7.3.4

### ISSUE THREAD

**Issue by i0gan** [casdoor/casdoor-php-sdk#36]
Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in E:\service\php\vendor\casdoor\casdoor-php-sdk\src\Auth\User.php on line 289

Remove array's indentifer can solve this problem.

**Comment by hsluoyz** [comment]
@i0gan hi, can you make a PR to fix it?

**Comment by i0gan** [comment]
Yes! No problem!

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/casdoor/casdoor-php-sdk/pull/39
